# Generated by Django 5.2.13 on 2026-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_type_id',
            field=models.IntegerField(choices=[(0, 'Individual'), (1, 'Restaurant'), (2, 'Community Group'), (3, 'Young Professional'), (4, 'Families')]),
        ),
    ]
