# Generated by Django 5.2.12 on 2026-03-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_producerprofile_business_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='default_delivery_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_business_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='is_charity_or_education',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
