# Generated by Django 5.2.12 on 2026-03-06 16:23

import uuid
from django.db import migrations, models


def backfill_user_id(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for u in User.objects.filter(user_id__isnull=True).only("id"):
        u.user_id = uuid.uuid4()
        u.save(update_fields=["user_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_id_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="user",
            name="customer_type_id",
            field=models.IntegerField(
                blank=True,
                null=True,
                choices=[
                    (0, "Individual"),
                    (1, "Restaurant"),
                    (2, "Community Group"),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(null=True, blank=True, editable=False),
        ),
        migrations.RunPython(backfill_user_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]