# Generated by Django 5.2.12 on 2026-03-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
        ('accounts', '0004_alter_user_email'),
    ]

    operations = [
    ]
