# Generated by Django 5.2.11 on 2026-02-27 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('VEGETABLES', 'Vegetables'), ('DAIRY_EGGS', 'Dairy & Eggs'), ('BAKERY', 'Bakery'), ('PRESERVES', 'Preserves'), ('SEASONAL', 'Seasonal Specialties'), ('OTHER', 'Other')], max_length=32)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit price in GBP (or your site currency).', max_digits=10)),
                ('unit', models.CharField(help_text="e.g., 'kg', 'Dozen', 'Jar', 'Loaf'", max_length=40)),
                ('availability', models.CharField(choices=[('AVAILABLE', 'In Season (Available)'), ('OUT_OF_SEASON', 'Out of Season'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', help_text='Season / availability status shown to customers.', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Current inventory available for ordering.')),
                ('allergens', models.CharField(blank=True, default='', help_text="Comma-separated allergens, e.g., 'eggs, milk'. Leave blank for none.", max_length=255)),
                ('harvest_date', models.DateField(blank=True, help_text='Harvest/collection date (if applicable).', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(help_text='The producer (seller) who owns this listing.', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'availability'], name='catalog_pro_categor_8352f2_idx'), models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx')],
            },
        ),
    ]
