# Generated by Django 5.2.13 on 2026-05-06 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organic_status',
            field=models.CharField(choices=[('CERTIFIED', 'Certified Organic'), ('NON_CERTIFIED', 'Not Certified Organic')], default='NON_CERTIFIED', help_text='Organic certification status for filtering and display.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organic_status'], name='catalog_pro_organic_450a54_idx'),
        ),
    ]
