# Generated by Django 5.2.14 on 2026-05-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productreview'),
        ('catalog', '0003_normalize_legacy_seasonal_category'),
        ('catalog', '0003_product_low_stock_threshold_and_more'),
    ]

    operations = [
    ]
