# Generated by Django 5.2.12 on 2026-03-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('READY', 'Ready for Collection/Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('READY', 'Ready for Collection/Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
