# Generated by Django 5.2.12 on 2026-03-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_alter_orderstatushistory_status'),
        ('orders', '0002_orderitem_status'),
    ]

    operations = [
    ]
