# Generated by Codex on 2026-05-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        ("orders", "0004_alter_orderitem_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurringOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("template_name", models.CharField(blank=True, max_length=120)),
                ("recurrence_interval", models.CharField(choices=[("WEEKLY", "Weekly"), ("FORTNIGHTLY", "Fortnightly")], default="WEEKLY", max_length=12)),
                ("order_weekday", models.PositiveSmallIntegerField(choices=[(0, "Monday"), (1, "Tuesday"), (2, "Wednesday"), (3, "Thursday"), (4, "Friday"), (5, "Saturday"), (6, "Sunday")])),
                ("delivery_weekday", models.PositiveSmallIntegerField(choices=[(0, "Monday"), (1, "Tuesday"), (2, "Wednesday"), (3, "Thursday"), (4, "Friday"), (5, "Saturday"), (6, "Sunday")])),
                ("delivery_address", models.TextField()),
                ("delivery_postcode", models.CharField(max_length=20)),
                ("delivery_instructions", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("PAUSED", "Paused"), ("CANCELLED", "Cancelled")], default="ACTIVE", max_length=10)),
                ("next_order_date", models.DateField()),
                ("next_delivery_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.ForeignKey(help_text="Restaurant customer who owns this recurring order template", on_delete=django.db.models.deletion.CASCADE, related_name="recurring_orders", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecurringOrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=120)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("producer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recurring_order_items_as_producer", to=settings.AUTH_USER_MODEL)),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="recurring_order_items", to="catalog.product")),
                ("recurring_order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.recurringorder")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RecurringOrderItemOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scheduled_order_date", models.DateField()),
                ("quantity", models.PositiveIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recurring_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="overrides", to="orders.recurringorderitem")),
            ],
            options={
                "ordering": ["recurring_item_id"],
            },
        ),
        migrations.AddIndex(
            model_name="recurringorder",
            index=models.Index(fields=["customer", "status"], name="orders_recu_customer_0ea63a_idx"),
        ),
        migrations.AddIndex(
            model_name="recurringorder",
            index=models.Index(fields=["next_order_date"], name="orders_recu_next_or_965415_idx"),
        ),
        migrations.AddConstraint(
            model_name="recurringorderitemoverride",
            constraint=models.UniqueConstraint(fields=("recurring_item", "scheduled_order_date"), name="unique_recurring_item_override_per_schedule"),
        ),
    ]
