# Generated by Django 5.2.14 on 2026-05-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_producer_delivery_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recurringorder',
            new_name='orders_recu_custome_0fbb8a_idx',
            old_name='orders_recu_customer_0ea63a_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringorder',
            new_name='orders_recu_next_or_6d8e8c_idx',
            old_name='orders_recu_next_or_965415_idx',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='quantity x unit_price', max_digits=10),
        ),
    ]
