# Generated by Django 5.2.5 on 2026-02-27 00:00

import decimal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_reference", models.CharField(max_length=100)),
                ("transaction_reference", models.CharField(max_length=100, unique=True)),
                ("producer_reference", models.CharField(max_length=100)),
                ("customer_reference", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=4, default=decimal.Decimal("0.1000"), max_digits=5),
                ),
                ("commission_amount", models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ("net_amount", models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SettlementBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("producer_reference", models.CharField(max_length=100)),
                ("week_start", models.DateField()),
                ("week_end", models.DateField()),
                ("total_gross", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                (
                    "total_commission",
                    models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12),
                ),
                ("total_net", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("PAID", "Paid")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-week_end", "-created_at"]},
        ),
        migrations.CreateModel(
            name="SettlementItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_item",
                        to="payments.paymentrecord",
                    ),
                ),
                (
                    "settlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="payments.settlementbatch",
                    ),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.AddConstraint(
            model_name="settlementbatch",
            constraint=models.UniqueConstraint(
                fields=("producer_reference", "week_start", "week_end"),
                name="unique_settlement_per_producer_week",
            ),
        ),
    ]
