# Generated by Django 5.2.5 on 2026-03-08

import decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrecord",
            name="commission_rate",
            field=models.DecimalField(decimal_places=4, default=decimal.Decimal("0.0500"), max_digits=5),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="payment_provider",
            field=models.CharField(default="STRIPE_TEST", max_length=30),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="provider_payment_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="checkout_session_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="paymentrecord",
            name="checkout_session_url",
            field=models.URLField(blank=True),
        ),
    ]
