# Generated by Django 5.2.12 on 2026-03-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentrecord_stripe_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='checkout_session_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
