# Generated by Django 5.2.11 on 2026-03-03 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerProfile',
            fields=[
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('business_postcode', models.CharField(max_length=20)),
                ('lead_time_hours', models.IntegerField(default=24)),
                ('verification_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
